categories:
- RNA
- Sequence Analysis
description: Computational detection of canonical microRNAs
homepage_url: https://github.com/Bierinformatik/miRNAture
long_description: |
**miRNAture** detects *bona fide* miRNA candidates through sequence homology
searches and validation steps using structural alignments with
pre-defined or/and modified miRNA-specific covariance models. The
miRNAture pipeline is composed of three modules: (1) Homology search
operating on miRNA precursors, (2) prediction of the positioning of
mature miRNAs within the precursor mature annotation, and (3) an
Evaluation scheme designed to identify false positive miRNA annotations.
This multi-stage approach generates annotation files in BED/GFF3 from
precursors and detected mature regions and corresponding FASTA files. At
the same time, a summary file with the MFE, precursor length and number
of loci of each annotated miRNA family.
name: miRNAture
owner: Cristian Velandia
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/mirnature
type: unrestricted
